//
// Created by metopa on 7.5.15.
//

#ifndef HTTP_SERVER_CEXTERNALCONTENT_H
#define HTTP_SERVER_CEXTERNALCONTENT_H

#include "CAbstractContent.h"

#include <string>

/**
 * This class represents a content generator entity.
 * It generates HTML page that contains a data generated by an executable program or a script.
 */
class CExternalContent : public CAbstractContent {
public:
	/**
	 * Constructs content object.
	 * Initializes some private attributes.
	 *
	 * \param userPath - A resource path as requested by user.
	 * \param realPath - A resource path that refers to the real resource location on a local machine.
	 * \param isScript - A boolean flag that defines if the requested resource is a bash script or not.
	 * \param wrapNeeded - A boolean flag that defines if the requested resource generates a prepared HTML page or raw data that is needed to be wrapped.
	 */
	CExternalContent( string const& userPath, string const& realPath, bool isScript,
					  bool wrapNeeded = true );

	virtual ~CExternalContent() { }

	/**
	 * This method executes the resource, saves data that thr resource has sent on standard out
	 * and wraps it into an HTML page.
	 */
	virtual void load();

	virtual const char * getModTime() const override;

private:
	string rawData_m;
	/**< A container fo generated data. */
	bool wrapNeeded_m;
	/** A boolean flag that defines if the requested resource generates a prepared HTML page or raw data that is needed to be wrapped.*/
	bool isScript_m; /**< A boolean flag that defines if the requested resource is a bash script or not. */

	/** This method wraps low-level function calls that are related to the process start.
	 *  It creates a pipe and redirects an output of the started process to the server process.
	 *  Then it calls a readPipe method to save the generated data into the rawData_m.
	 */
	void exec();

	/**
	 * This method reads data from a pipe and saves it into the rawData_m.
	 * \param fd - A system file descriptor that refers to the pipe.
	 */
	void readPipe( int fd );
};


#endif //HTTP_SERVER_CEXTERNALCONTENT_H
